ALTER TABLE leads ADD COLUMN IF NOT EXISTS prenom TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS societe TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS objectif TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS horizon_decision TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS opt_in_politique BOOLEAN DEFAULT FALSE;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS opt_in_partenaire BOOLEAN DEFAULT FALSE;
